name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 */24 * * *" 
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
    - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Vik154/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - name: >-
          🌸 Anilist watch list and reading list - Favorites anime and currently
          watching
        uses: Vik154/metrics@latest
        with:
          token: NOT_NEEDED
          plugin_anilist: 'yes'
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1
          use_mocked_data: 'yes'
          verify: 'yes'
      - name: >-
          🌸 Anilist watch list and reading list - Favorites manga and currently
          reading
        uses: Vik154/metrics@latest
        with:
          token: NOT_NEEDED
          plugin_anilist: 'yes'
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, reading
          plugin_anilist_limit: 1
          use_mocked_data: 'yes'
          verify: 'yes'
      - name: 🌸 Anilist watch list and reading list - Favorites characters
        uses: Vik154/metrics@latest
        with:
          token: NOT_NEEDED
          plugin_anilist: 'yes'
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22
          use_mocked_data: 'yes'
          verify: 'yes'
