name: TEST_METRICS

on:
  # Schedule daily updates
  schedule:
    - cron: "0 */24 * * *" 
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push:
  #  branches:
  #  - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build Metrics
        uses: Vik154/metrics@latest
        with:
          output_action: commit
          committer_branch: Vik154-metrics_output
          committer_message: "chore: update metrics"
          filename: my-metrics-0.svg

      - name: Build test template
        uses: Vik154/metrics@latest
        with:
          filename: metrics.classic.svg
          committer_branch: Vik154-metrics_output
          committer_message: "chore: update metrics classic template"
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
