name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 */24 * * *" 
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push:
  #  branches:
  #  - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ♐ Random code snippet - JavaScript or TypeScript snippet of the day
        uses: Vik154/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_code: 'yes'
          plugin_code_languages: javascript, typescript
          plugin_code_load: 400
          use_mocked_data: 'yes'
          verify: 'yes'
